AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/*_spec.rb
Metrics/MethodLength:
  Exclude:
    - spec/*_spec.rb
Naming/MethodParameterName:
  Exclude:
    - lib/probability.rb
    - lib/positives.rb
Naming/AccessorMethodName:
  Exclude:
    - lib/jra/pages.rb
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Style/RedundantSelf:
  Exclude:
    - lib/probability.rb
    - lib/positives.rb
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedColonStyle: table
