AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/*_spec.rb
Naming/MethodParameterName:
  Exclude:
    - lib/probability.rb
    - lib/positives.rb
Style/RedundantSelf:
  Exclude:
    - lib/probability.rb
    - lib/positives.rb
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent