export SIMULATOR_FIRST_WAIT=10
export SIMULATOR_END_WAIT=10

# export SCHEDULER_DEADLINE_ROOM_UNTIL_FIRE=10

# export UMA_LEARNING_INTERVAL=100
# export UMA_LEARNING_WAIT=0.02
# export UMA_IDLING_WAIT=1.0
export UMA_CONVERGE_ERROR_TOLERANCE=1e-4

export ODDS_ANALYZER_LEARNING_RATE=0.0001
# export ODDS_ANALYZER_PROBABLE_EFFICIENCY=0.05
# export ODDS_ANALYZER_PROBABLE_GUARANTY=0.6
# export ODDS_ANALYZER_PROBABLE_RETURN=0.8
export ODDS_ANALYZER_DEBUG="false"
