export SIMULATOR_FIRST_WAIT=10
export SIMULATOR_END_WAIT=10
# export SCHEDULER_DEADLINE_ROOM_UNTIL_FIRE=10
# export UMA_LEARNING_INTERVAL=100
# export UMA_LEARNING_WAIT=0.02
# export UMA_IDLING_WAIT=1.0